Feature/#7 model 코드 작성
HephaestusProject/pytorch-binaryconnect pull request #21
Opened 2020-09-12 08:35 UTC by ssaru

# Pull Request
레파지토리에 기여해주셔서 감사드립니다.

해당 PR을 제출하기 전에 아래 사항이 완료되었는지 확인 부탁드립니다:
- [x] 작성한 코드가 어떤 에러나 경고없이 빌드가 되었나요?
- [x] 충분한 테스트를 수행하셨나요?

## 1. 해당 PR은 어떤 내용인가요?

- BinarizedLinear, BinarizedConv 모델 작성

## 2. PR과 관련된 이슈가 있나요?

Refs: #7

2020-09-12 12:54 UTC, inmoonlight commented on conf/conv/model/model.yaml
> +    mode: Stocastic
```suggestion
    mode: Stochastic
```

2020-09-12 12:56 UTC, inmoonlight commented on conf/mlp/model/model.yaml
> +    mode: Stocastic
```suggestion
    mode: Stochastic
```

2020-09-12 12:56 UTC, inmoonlight commented on conf/conv/runner/runner.yaml
> +        distributed_backend: "ddp"
이것만 ""를 사용하셨는데 혹시 다른 이유가 있나요?

2020-09-12 12:58 UTC, inmoonlight commented on src/model/net.py
> +
PEP8에서는 2줄 공백을 권장합니다!

2020-09-12 13:00 UTC, inmoonlight commented on src/model/net.py
> +class BinaryLinear(nn.Module):
LN7에서 import하고 있는 BinaryLinear와 클래스명이 같습니다

2020-09-12 13:25 UTC, ssaru commented on conf/conv/runner/runner.yaml
> +        distributed_backend: "ddp"
이 부분은 그냥 `ddp`라고 적어도 될 것 같습니다.
말씀해주셔서 감사합니다.

2020-09-12 13:25 UTC, ssaru commented on conf/conv/model/model.yaml
> +    mode: Stocastic
으앗..... 이거 안바꿨군요 😢
감사합니다.

2020-09-12 13:26 UTC, ssaru commented on src/model/net.py
> +
엇.. 감사합니다.🙇‍♂️

2020-09-12 13:27 UTC, ssaru commented on src/model/net.py
> +class BinaryLinear(nn.Module):
부끄럽군요 😢

2020-09-12 13:35 UTC, inmoonlight commented on src/model/net.py
> +        self.fc1 = BinaryLinear(width * height * channels, 1024, bias=False, mode="Stocastic")
```suggestion
        self.fc1 = BinaryLinear(width * height * channels, 1024, bias=False, mode="Stochastic")
```

2020-09-12 13:47 UTC, inmoonlight commented on src/model/net.py
> +        self.relu = nn.ReLU()
지금 보면 init에 반복되는 building block 이 등장하는데요, 이런 경우 하나의 반복 최소 단위를 함수로 만들면 가독성도 좋아지고, 코드가 깔끔해져요. 🤗 

```suggestion
    def linear_block(dim_in, dim_out, bias=False, mode="Stochastic"):
        return nn.Sequential(
            BinaryLinear(dim_in, dim_out, bias=bias, mode=mode),
            nn.BatchNorm1d(dim_out),
            nn.ReLU()
        )

        self.linear_block1 = linear_block(width * height * channels, 1024)
        self.linear_block2 = linear_block(1024, 1024)
        self.linear_block3 = linear_block(1024, 1024)
        self.linear = BinaryLinear(1024, classes)
```

2020-09-12 13:47 UTC, inmoonlight commented on src/model/net.py
> +        self.fc3 = nn.BinarizedLinear(1024, classes)
https://github.com/HephaestusProject/pytorch-binaryconnect/pull/21/commits/9e8665bdbf24d051e1de3e837b0dbfd95024286f#r487411548 코멘트와 유사하게 바꾸면 좋을 것 같아요

2020-09-12 13:53 UTC, inmoonlight commented on train.py
> +        model=runner, train_dataloader=train_dataloader, val_dataloaders=test_dataloader,
여기서는 `val`과 `test`가 동일한데 `runner.py` 에서는  `val`과 `test`를 구분해서 헷갈릴 수 있다고 생각합니다!

2020-09-12 13:55 UTC, inmoonlight commented on src/runner/runner.py
> +        return {"loss": test_loss, "acc": test_acc}
validation 과 test 가 많은 부분에서 코드가 중복된다고 생각합니다.
다른 부분은 outputs의 key 값인데요, 이게 맥락없이 하드코딩되어있어서 위험할 수 있다고 생각합니다.

그리고 validation 과 test 의 경계가 모호한 것 같은데 (`train.py`) 여기서는 구분하신 이유가 있을까요?

2020-09-12 14:17 UTC, inmoonlight requested changes
@ssaru 리뷰내용 확인해주세요 🤗

2020-09-13 11:31 UTC, ssaru commented on src/runner/runner.py
> +        return {"loss": test_loss, "acc": test_acc}
지형님! 이 부분은 train 코드를 본격적으로 짤 때 반영할까 하는데... 괜찮을까요?!

2020-09-13 11:38 UTC, ssaru commented
@inmoonlight 지형님, 말씀하신 내용 일부 반영했습니다.
train.py의 피드백은 추후 train파트 작성시에 반영할까하는데, 한번 확인 부탁드릴게요! 🙇‍♂️

2020-09-14 12:21 UTC, aisolab commented on conf/conv/model/model.yaml
> +    mode: &mode stochastic
`&`는 어떤 의미일까요?

2020-09-14 12:21 UTC, aisolab commented on conf/conv/model/model.yaml
> +            - in_channels: *in_channels
`*`는 어떤 의미일까요?

2020-09-14 12:21 UTC, aisolab commented on conf/conv/model/model.yaml
> +                      ceil_mode: false
개인적으로 느낀바 default parameter에 대한 value도 전부 써주신 것 같은 데, overriding을 하는 parameter만 기입하는 건 어떨까요? 개인의 선택문제일 것 같긴하지만 config 파일이 너무 늘어져보이는 것 같습니다.

2020-09-14 12:47 UTC, ssaru commented on conf/conv/model/model.yaml
> +    mode: &mode stochastic
&in_channels라는 변수를 만들어서 거기에 3이라는 값을 넣겠다는 의미입니다.
이는 yaml파일에서 gloabl variable로 사용됩니다.

2020-09-14 12:47 UTC, ssaru commented on conf/conv/model/model.yaml
> +            - in_channels: *in_channels
global variable인 in_channels의 값을 불러온다는 의미입니다.

2020-09-14 12:48 UTC, ssaru commented on conf/conv/model/model.yaml
> +                      ceil_mode: false
좋습니다. 지형님도 말씀해주셔서 하면서 저도 그게 약간 고민이긴했는데요.
그게 맞는 방향 같네요.

2020-09-14 12:59 UTC, inmoonlight requested changes
@ssaru 보섭님도 말씀해주셨지만, 어디까지 구조를 쉽게 변형할 수 있게 할 것인가? 에 대해서 지금보다는 그 수준을 낮추면 좋을 것 같습니다. 그 외엔 좋아요!

궁금한 것은 train.py의 수정 부분인데, 요건 config가 바뀌면서 수정된 것인가요?

2020-09-14 13:17 UTC, ssaru commented
@inmoonlight 
별도로 수정하진 않았는데요.
아마도 isort와 black의 영향이지 않을까 싶습니다.
저번 commit 때, 누락된 내용이 약간 있긴 있었는데,,, 그거 영향인지는 잘 모르겠네요 ㅠㅠ

2020-09-15 15:45 UTC, aisolab commented on conf/conv/model/model.yaml
> +    mode: &mode stochastic
오.... 그런것이었군요.

2020-09-15 15:45 UTC, aisolab commented on conf/conv/model/model.yaml
> +            - in_channels: *in_channels
오.... 그런것이었군요.

2020-09-21 14:06 UTC, aisolab approved these changes

2020-10-02 08:56 UTC, ssaru commented
@aisolab @inmoonlight 
PR 반영 완료하였습니다.

확인 부탁드리겠습니다.  🙇‍♂️

2020-10-16 09:14 UTC, dreamgonfly commented on src/model/net.py
> +            self.batch_norm = nn.BatchNorm2d(num_features=out_channels)
self.batch_norm의 타입이 boolean 변수였다가 nn.Module로 바뀌는데 헷갈릴 것 같습니다. boolean 변수와 nn.Module의 이름을 다르게 주는 것이 어떨까요? 예컨대 use_batch_norm 처럼요.

2020-10-16 09:16 UTC, dreamgonfly commented on src/model/net.py
> +            self.activation = getattr(nn, activation["type"])(**activation["args"])
위와 같은 의견입니다!

https://github.com/HephaestusProject/pytorch-binaryconnect/pull/21/files#r506206919

2020-10-16 09:28 UTC, dreamgonfly commented on src/model/net.py
> +            self.pool = getattr(nn, pool_dict["type"])(**pool_dict["args"])
config를 파싱하는 부분은 모델 정의에서 담당하는게 맞지 않는 것으로 보이는데.. 이걸 모델을 초기화하기 전에 이 부분을 먼저 처리하고 모델 쪽에 넘겨주는 게 낫지 않을까요?

2020-10-16 09:29 UTC, dreamgonfly requested changes
코멘트 몇개 드렸습니다!

2020-10-19 15:56 UTC, ssaru commented on src/model/net.py
> +            self.batch_norm = nn.BatchNorm2d(num_features=out_channels)
오! 네 좋습니다!
안그래도 코드를 작성하면서 그 부분 고민을 했었는데, 역시나 그렇게 푸는게 맞을 것 같습니다.

2020-10-19 15:57 UTC, ssaru commented on src/model/net.py
> +            self.pool = getattr(nn, pool_dict["type"])(**pool_dict["args"])
오... 맞는 말씀이신 것 같습니다! 감사합니다!

2020-10-19 15:58 UTC, ssaru commented
@dreamgonfly 
용래님 신경써서 해주신 코멘트 감사드립니다.
많은 도움이 되었습니다.
다음 작업 때, 참고하여 작업하도록 하겠습니다. 🙇‍♂️

2020-11-07 07:07 UTC, merged